### ISSUE TITLE
Does not work with `resolve.alias`

### ISSUE THREAD

**Issue by maksimsemenov** [amoutonbrady/vite-plugin-solid#3]
When I'm trying to use `vite-plugin-solid` with vite config `resolve.alias` property, the aliases are not replaced.

```js
// vite.config.js

import { defineConfig } from 'vite'
import solidPlugin from 'vite-plugin-solid'

export default defineConfig({
  resolve: {
    alias: {
      views: './src/views',
    }
  },
  // plugins: [solidPlugin()],
  server: {
    port: 1234
  }
})
```

```js
// index.tsx

import { render } from 'solid-js/web'
import { Root } from 'views/App/Root'

render(() => <Root />, document.getElementById('app'))

```

Then, when I try to start vite server, I'm getting an error:
```
Error: The following dependencies are imported but could not be resolved: views/App/Root 
```

If I disable the plugin, vite will start the server

**Comment by amoutonbrady** [comment]
This is has been released in version `1.2.3`

**Comment by langbamit** [comment]
@amoutonbrady 
This work:
```js
...
resolve: {
    alias: [
      { find: 'views', replacement: './src/views' },
    ]
  },
...
```

But this don't work:
```js
...
resolve: {
    alias: {
      views: './src/views',
    }
  },
...
``

**Comment by amoutonbrady** [comment]
Ah, I see.. that's an odd syntax.. I used a package that automatically handles deep merging but I guess it gets stuck on trying to merge an object into an array. I guess I'll have to do a bit of a manual work there.

Thanks for bringing that up to my attention :)

**Comment by amoutonbrady** [comment]
@langbamit For what it's worth, top level `alias` is deprecated:

![image](https://user-images.githubusercontent.com/17355226/111827567-52ee3600-88ea-11eb-92dc-8b2ea0e02060.png)

https://vitejs.dev/config/#resolve-alias
