### ISSUE TITLE
Unpredictable behavior of solid components

### ISSUE THREAD

**Issue by MrFoxPro** [amoutonbrady/vite-plugin-solid#6]
Hi.
I'm trying to use imported component from another file
// home.tsx
```jsx
export default function Home() {
    ...
    return <div />
}
```

// file with issue
```jsx
import Home from './home';

function Test(){
    return <div />
}
export default function App(){
    const home = <Home />;
    const test = <Test />;
    console.log(typeof home, typeof test); //prints function, object
}
```
With vite production build / webpack & babel build `console.log(typeof <Home />)` -> `object`
With vite and this plugin in dev mode `console.log(typeof <Home />)` -> `function`

I need to <Home /> to be always object to use in another library as dom element.
Thanks in advance.

**Comment by MrFoxPro** [comment]
The problem appears only with imported components as default.

**Comment by MrFoxPro** [comment]
```ts
export default defineConfig({
  plugins: [solidPlugin()],
  build: {
    target: 'esnext',
    outDir: './distribution/vite',
    rollupOptions: {
      input: {
        devices: path.resolve(__dirname, 'source/devices/index.html'),
        main: path.resolve(__dirname, 'source/main/index.html'),
        chat: path.resolve(__dirname, 'source/chat/index.html'),
      },
      output: {
        esModule: true,
        format: 'es',
      },
    },
  },
  css: {
    modules: {
      localsConvention: 'camelCase',
      generateScopedName: '[local]-[hash:base64:2]',
    },
  },
  resolve: {
    alias: [
      {
        find: '@',
        replacement: path.resolve(__dirname, './source'),
      },
    ],
  },
});
```
vite config
tried different esbuild and rollup commonjs settings, but with now success

**Comment by ryansolid** [comment]
It is the extra wrapper HMR adds. In order for swapping to work it wraps each default export component (module boundary) with a `createMemo`.  Unfortunately this is the only way I could think of for containing HMR. Solid's components are just functions so need to introduce something contain reactivity, to act as a nested mount point.

**Comment by MrFoxPro** [comment]
> It is the extra wrapper HMR adds. In order for swapping to work it wraps each default export component (module boundary) with a `createMemo`. Unfortunately this is the only way I could think of for containing HMR. Solid's components are just functions so need to introduce something contain reactivity, to act as a nested mount point.
disabling hot in solid-vite-plugin fixed issue. thank you!
